# Generated by Django 3.0.2 on 2022-01-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date_id', models.DateField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('quarters', models.CharField(max_length=10)),
                ('quarter', models.CharField(max_length=20)),
                ('months', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('weeks', models.CharField(max_length=10)),
                ('week', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Championships',
            fields=[
                ('championship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('championship_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400, null=True)),
                ('location', models.CharField(max_length=250)),
                ('date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('School', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_picture', models.ImageField(null=True, upload_to='')),
                ('event_description', models.CharField(max_length=250)),
                ('championship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Championships')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('championship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Championships')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=15)),
                ('championship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Championships')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Teams')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidb.Users')),
            ],
        ),
    ]
