# Generated by Django 3.0.2 on 2022-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidb', '0002_auto_20220113_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='championships',
            name='championship_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
