# Generated by Django 3.0.2 on 2022-01-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidb', '0003_championships_championship_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='championship_id',
        ),
        migrations.AlterField(
            model_name='championships',
            name='date_id',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
