# Generated by Django 3.0.2 on 2022-01-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidb', '0004_auto_20220113_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Championships',
            new_name='Championship',
        ),
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
